Feature/t 78 intake v2 migration
ukaea/fair-mast pull request #96
Opened 2024-11-25 16:32 UTC by khalsz

here is a demo from the load_data.ipynb
![image](https://github.com/user-attachments/assets/6fb846d2-f71b-4f26-b16a-8cbb47f74dfd)

2024-11-26 12:36 UTC, NathanCummings commented
Could I ask for a couple of things:
1. Could you pull in the updated CI - I suspect some of the formatting checks will fail and need fixing. The CI wasn't checking it before but it is now (in main).
2. Could you remove unnecessary output from the documentation notebooks, like the from the blocks that install dependencies.

2024-11-26 12:52 UTC, NathanCummings commented
Could you also check through the documentation to make sure it all still works with the new catalog? I just checked and the first block in Quickstart failed for me.

2024-11-26 12:59 UTC, NathanCummings commented
Sorry, also, I think we need aliases for the entries.

2025-01-27 15:32 UTC, samueljackson92 requested changes
Looks good to me, but we need to change the paths in the notebooks back to `https://mastapp.site/intake/catalog.yaml` from a uri that is specific to your machine.

2025-01-30 08:11 UTC, samueljackson92 approved these changes
Looks good. Thanks Khalid

2025-01-30 08:11 UTC, merged